version: '3.8'

services:
  start-abot:
    image: startagainco/start-abot:latest
    build:
      context: .
      args:
        - NODE_VERSION=15.0.1
    environment:
      - TOKEN=${TOKEN}
      - NODE_ENV=production
