ARG NODE_VERSION

FROM node:${NODE_VERSION} AS build

COPY . /start-abot

WORKDIR /start-abot

RUN yarn cache clean --force
RUN rm -rf node_modules
RUN yarn install --production

FROM node:${NODE_VERSION}
WORKDIR /start-abot
COPY --from=build /start-abot /start-abot

ENTRYPOINT ["yarn", "start"]
