name: Build docker image

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

jobs:
  build-docker:
    name: Build and push docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker-image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker build -f ./docker/Dockerfile.prod --build-arg NODE_VERSION=15.0.1 -t startagainco/start-abot:latest -t startagainco/start-abot:${GITHUB_REF:11} .
          docker push startagainco/start-abot:${GITHUB_REF:11}
          docker push startagainco/start-abot:latest
          docker logout
