name: Build docker image

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Get the repository release version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Docker image
        run: |
          docker build . \
          -f ./docker/Dockerfile.prod \
          --build-arg NODE_VERSION=15.0.1 \
          -t startagainco/start-abot:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run : docker push startagainco/start-abot:${{steps.vars.outputs.tag}}
      - name: Build the latest Docker image
        run: |
          docker build . \
          -f ./docker/Dockerfile.prod \
          --build-arg NODE_VERSION=15.0.1 \
          -t startagainco/start-abot:latest
      - name: Push the latest Docker image
        run : docker push startagainco/start-abot:latest
      - name: Lougout from DockerHub Registry
        run: docker logout
