name: Test action

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Tag ${GITHUB_REF:11}"
        echo "Tag ${GITHUB_REF}"
